### ISSUE TITLE
Support for singular tool calls? (unclosed `</tool-calls>`)

### ISSUE THREAD

**Issue by SJCaldwell** [dreadnode/rigging#3] opened 2024-04-10 15:41 UTC
Hey guys! 

Love the work, rigging is a great library. 

I was checking out the tool calling example provided in the docs using gpt-4 turbo. 

```python
from typing import Annotated
import rigging as rg

class WeatherTool(rg.Tool):
    @property
    def name(self) -> str:
        return "weather"

    @property
    def description(self) -> str:
        return "A tool to get the weather for a location"

    def get_for_city(self, city: Annotated[str, "The city name to get weather for"]) -> str:
        print(f"[=] get_for_city('{city}')")
        return f"The weather in {city} is nice today"

chat = (
    rg.get_generator("gpt-4-turbo")
    .chat(
        [
            {"role": "user", "content": "What is the weather in London?"},
        ]
    )
    .using(WeatherTool())
    .run()
)

# [=] get_for_city('London')

print(chat.last.content)

# "Based on the information I've received, the weather in London is nice today."
```
Rigging seems to be failing to parse the xml call. My output (with logging turned on) is:

`2024-04-10 10:24:11.443 | DEBUG    | rigging.chat:_until_tools_callback:218 - No tool calls or types, returning message`

*from gpt4-turbo*:
```xml
<tool-calls>
   <tool-call tool="weather" function="get_for_city">
      <parameter name="city" value="London" />
   </tool-call>
```

*from claude-2.1*
```xml
'<tool-calls>\n   <tool-call tool="weather" function="get_for_city">\n      <parameter name="city">London</parameter>\n   </tool-call>
```
Which, in fairness, does seem to be an incomplete call on the model's part, with the model failing to close `<tool-calls>` as shown in the system prompt example. It has been pretty consistent for me, between claude and gpt4 though, so maybe adding support for extracting individual tool calls would be useful even if a complete list of tool calls isn't completed.

**Comment by monoxgas** [comment] 2024-04-10 22:39
Nice catch, this is caused by certain APIs not returning the stop sequence as part of their response. Originally I added the end XML tag for the `ToolCalls` model to stop sequences to speed up things, but we'll remove this for now until a better solution is found.

I also added a `force: bool` flag to the `using()` function to return an error to the model if it doesn't use a tool in it's first response. This flag is cleared after a tool call succeeds. This feature will likely need some long term adapting as well, but should be a stop-gap for models which are hesitant to make tool calls in the first exchange.

Consider this resolved with [v0.2.1](https://github.com/dreadnode/rigging/compare/v0.2.0...v0.2.1)

**Closed by monoxgas** 2024-04-10 22:39 UTC
